spring:
  application:
    name: BookWise

  datasource:
    url: jdbc:mysql://localhost:3306/BookWise?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8080
jwt:
  secret: 5367566B5970337336763979244226452948404D635166546A576E5A7234753778214125442A472D4B6150645367566B5970
  expiration: 8640000
